### ISSUE TITLE
Playtype Data

### ISSUE THREAD

**Issue by TW97** [seemethere/nba_py#107]
I was curious if anyone had looked into getting Playtype data for teams and players?

**Comment by bttmly** [comment]
Do you mean the data from screens like this https://stats.nba.com/players/transition/ ?

I've implemented this in my JS client https://github.com/bttmly/nba/blob/master/src/synergy.js but porting it to python should be pretty easy. The URLs and parameters are the top of the file are pretty much all you should need. Ultimately you'll construct URLs like the following https://stats-prod.nba.com/wp-json/statscms/v1/synergy/player/?name=offensive&seasonType=Reg&category=Transition&season=2017&limit=500
