### ISSUE TITLE
ConnectionError: ('Connection aborted.', error(13, 'Permission denied'))

### ISSUE THREAD

**Issue by vincenttern** [seemethere/nba_py#111]
I want to add nba scores to my blog website that is built with google app engine and python. I am getting a ConnectionError that I seem to can't fix. Any help will be greatly appreciated. Thanks!

**Comment by mneedham91** [comment]
We're going to need a lot more context. First of all, I bet the error message you are getting of ConnectionError is not related to nba_py but is actually related to Google App Engine. Can you please provide us with your code related to the error message?

**Comment by bttmly** [comment]
See #88 

NBA.com seems to block IP addresses from major cloud hosting providers (AWS, Google App Engine, etc)
