### ISSUE TITLE
Endpoint for player's date of birth

### ISSUE THREAD

**Issue by vladiki** [seemethere/nba_py#112]
Hello, 

Does anyone know which endpoint to use to get the player's date of birth?

**Comment by mneedham91** [comment]
PlayerSummary() in nba_py.player

```
from nba_py.player import PlayerSummary
print(PlayerSummary(player_id=201593).info())
```

will contain BIRTHDATE

**Comment by vladiki** [comment]
Thank you very much! To the moon!
