### ISSUE TITLE
Is there a endpoint to get Player Boxscore stats ?

### ISSUE THREAD

**Issue by romlr** [seemethere/nba_py#113]
Is there a endpoint to get results displayed in eg. 'http://stats.nba.com/player/1627732/boxscores-traditional/'

Comparable to endpoint 'playercareerstats' for results displayed at 'http://stats.nba.com/player/1627732/career/'

My point is to get stats and team encounterered for last N games, per player ID.

Thanks for your work which is monumental!

**Comment by romlr** [comment]
Think I got it:  It should be 'playergamelog' right ?

Thx

**Comment by bttmly** [comment]
Yeah that's the one. 

If I'm ever trying to figure out from which NBA page maps to which endpoint, I open up Chrome dev tools, go to Network tab, filter by XHR only (there should only be a few requests at that point), then just find the one with a long query string and that's almost always it.

**Comment by romlr** [comment]
fine thanks!
