### ISSUE TITLE
Could not open game details

### ISSUE THREAD

**Issue by gabrielfior** [seemethere/nba_py#13]
Hi, I could not get your game example to work. 
The following commands result in an error:

```
from nba_py import game
bs = game.Boxscore('0041400122')
print bs.game_summary()
```

Could you please tell me why it is not working?
Thanks,
Gabriel.

**Comment by jorgegil96** [comment]
Could you post the error?

**Comment by gabrielfior** [comment]
```
>>> bs = game.Boxscore('0041400122')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/gabrielfior/anaconda/lib/python2.7/site-packages/nba_py/game.py", line 21, in __init__
    'EndRange': end_range})
  File "/Users/gabrielfior/anaconda/lib/python2.7/site-packages/nba_py/__init__.py", line 42, in _get_json
    _get.raise_for_status()
  File "/Users/gabrielfior/anaconda/lib/python2.7/site-packages/requests/models.py", line 840, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: http://stats.nba.com/stats/boxscore/?GameID=0041400122&RangeType=0&StartPeriod=0&StartRange=0&EndPeriod=0&EndRange=0
```

**Comment by jorgegil96** [comment]
This is the same issue as #10 . stats.nba.com now requires a user-agent. I thought @seemethere fixed it. Maybe the changes are not in the stable version yet? We'll see...

**Comment by gabrielfior** [comment]
Not sure this helps, but another thing

```
>>> nba_py.BASE_URL
'http://stats.nba.com/stats/{endpoint}/'
>>> nba_py.HEADERS
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'module' object has no attribute 'HEADERS'
```

**Comment by gabrielfior** [comment]
Actually it now works. I looked at the last commit (https://github.com/seemethere/nba_py/commit/338654ea586b30ad2d01792ba864b174d0ab7cf3) and my __init__.py file was not the correct one.
I do not know why, since I installed the package today, but it was not updated.
Anyway, thanks for the reply.

**Comment by seemethere** [comment]
Oh I haven't updated the package on pypi yet. I'll update it by the end of this week.
