### ISSUE TITLE
Trying to install module on Cloud9 IDE

### ISSUE THREAD

**Issue by yoursweater** [seemethere/nba_py#20]
Hey, I'm sort of a coding noob but I'm trying to figure out how to use your API on Cloud9's cloud-based IDE and I'm running into some problems. Specifically, when I try to install the package using 

$ pip install . 

I receive the following error:
...
running install_lib
creating /usr/local/lib/python2.7/dist-packages/nba_py
error: could not create '/usr/local/lib/python2.7/dist-packages/nba_py': Permission denied

Any ideas on what I could do to fix this? I'm pretty sure it's somehow related to the fact that I'm running this on a cloud-based server and not off of my hard drive. Thanks!

**Comment by seemethere** [comment]
Can you try to do a `sudo pip install .`?

**Comment by yoursweater** [comment]
That worked! Thanks.
