### ISSUE TITLE
Player's PER

### ISSUE THREAD

**Issue by pawelad** [seemethere/nba_py#21]
Hi,

I've been looking for some time, but with no luck - does anybody know how to get player's [PER](https://en.wikipedia.org/wiki/Player_efficiency_rating) from the API?

Thanks in advance,
Paweł

**Comment by mcdallas** [comment]
PER is an espn stat. You wont find it on nba.com

**Comment by pawelad** [comment]
That's a shame then, but thanks for the answer.
