### ISSUE TITLE
Functions marked as "FORBIDDEN BY THE NBA" seems to work

### ISSUE THREAD

**Issue by ycheng517** [seemethere/nba_py#28]
I am able to successfully retrieve data from the following functions that were commented as "FORBIDDEN BY THE NBA": 

PlayerGeneralSplits
PlayerOpponentSplits
PlayerShootingSplits

I simply call the function with a player ID like following: 

```
stats_a = player.PlayerShootingSplits(player_id='203507')
print((stats_a.shot_5ft())
```

**Comment by seemethere** [comment]
This mistake was resolved by:
#45
