### ISSUE TITLE
Add player tracking stats for the entire league

### ISSUE THREAD

**Issue by mwilliammyers** [seemethere/nba_py#31]
This endpoint (`leaguedashptstats`) is similar to the one you already use for player e.g. [here](https://github.com/seemethere/nba_py/blob/1d640fe134676fd6400c3751c30f16dc828ff3fe/nba_py/player.py#L848) but for the entire league like [stats.nba.com](https://stats.nba.com) uses [here](http://stats.nba.com/tracking/#!/player/). I could get a PR together for this...

**Comment by seemethere** [comment]
Closed with #32
