### ISSUE TITLE
500 Server Error: Internal Server Error for url:

### ISSUE THREAD

**Issue by anditburns** [seemethere/nba_py#33]
getting the following 500 error when using any endpoint api:

raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: http://stats.nba.com/stats/commonplayerinfo?PlayerID=203112

**Comment by AlexNarayanan** [comment]
I'm getting a 400 error instead, bad request for URL

**Comment by anditburns** [comment]
This issue seems to have been resolved now. I was able to obtain stats on it last night.

**Comment by seemethere** [comment]
Okay awesome! Yeah it happens some times, out of our control!
