### ISSUE TITLE
Games endpoint not working

### ISSUE THREAD

**Issue by seanseany** [seemethere/nba_py#34]
**When I run the example_game.py file I get a 404. It was working last week so maybe the NBA changed their endpoint?**

Traceback (most recent call last):
  File "example_game.py", line 7, in <module>
    box = game.Boxscore('0041400122')
  File "/Library/Python/2.7/site-packages/nba_py/game.py", line 21, in **init**
    'EndRange': end_range})
  File "/Library/Python/2.7/site-packages/nba_py/**init**.py", line 74, in _get_json
    _get.raise_for_status()
  File "/Library/Python/2.7/site-packages/requests/models.py", line 844, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http://stats.nba.com/stats/boxscore?GameID=0041400122&RangeType=0&StartPeriod=0&StartRange=0&EndPeriod=0&EndRange=0

**Comment by seemethere** [comment]
Yeah it seems as though their internal boxscore webpage has been switched over to the boxscoresummaryv2 endpoint with a mix of the boxscoretraditionalv2 to do player summary boxscores.

**Comment by shyamkotak** [comment]
So is there no way to get that data through nba_py? @seemethere

**Comment by seemethere** [comment]
@shyamkotak As of right now no, but currently working on a fix

**Comment by gyerli** [comment]
Any update on this?

**Comment by grillazz** [comment]
@seemethere can this be closed by https://github.com/seemethere/nba_py/pull/48 ?

**Comment by seemethere** [comment]
Closed by #50
