### ISSUE TITLE
[Noob Question] How Can I Fix This ?

### ISSUE THREAD

**Issue by diomaiden** [seemethere/nba_py#4]
Hi. I am completly noob at Python and this module. I tried like this but it failed. How can I fix ?

from nba_py import team
A=team.TeamLineups(1610612765)
print(A)

result:
nba_py.team.TeamLineups object at 0x00000089FE5227F0

**Comment by seemethere** [comment]
You're going to need to actually use one of the included methods in the
class to access the data from the class. Or if you want theres also a
TeamLineups.json object available that can also be printed.

**Comment by diomaiden** [comment]
Thanks for helping
