### ISSUE TITLE
Requires recent version of requests

### ISSUE THREAD

**Issue by garionphx** [seemethere/nba_py#41]
Just in case anyone else comes across this, I was getting nothing but "400 Bad Request" errors. I eventually tracked it down to the fact I was running an old version of requests (2.8.1).. Upgrading to 2.10.0 fixed my issue.

**Comment by seemethere** [comment]
Awesome I'll add that to the README!

**Comment by osuhomebase** [comment]
I tried upgrading to 2.10.0 and that did not seem to work.  I still get 400 Bad Request.  Did you do anything else, or **just** update requests?

**Comment by seemethere** [comment]
Updated the package on pypi with v0.1a2 which should resolve these issues. (https://github.com/seemethere/nba_py/commit/0fb85bf7845917b9caf70fc49833060ca4f1e08e)
