### ISSUE TITLE
Authentication for API

### ISSUE THREAD

**Issue by kpelechrinis** [seemethere/nba_py#42]
I have tried to replicate the examples from the documentation page: https://github.com/seemethere/nba_py/wiki/stats.nba.com-Endpoint-Documentation but I obtain the following error: 

Access Denied

You don't have permission to access "http://stats.nba.com/stats/scoreboard/?" on this server.

Is an API key required now?

**Comment by sdpetrides** [comment]
I have tried

curl "http://stats.nba.com/stats/scoreboard/?GameDate=02/14/2015&LeagueID=00&DayOffset=0"

in my terminal and I got the same "You don't have permission to access" response. I think there may be an access key required. My other thought is that since it is the NBA offseason they have blocked off the api for maintenance.

**Comment by grillazz** [comment]
Hello, Tried version 0.1a2 but it is not solving issue and only this:
```curl -H "Referer: http://stats.nba.com/scores/" "http://stats.nba.com/stats/teaminfocommon/?SeasonType=Regular+Season&Season=2014-15&TeamID=1610612737&LeagueID=00"```

```json
{"resource":"teaminfocommon","parameters":{"LeagueID":"00","Season":"2014-15","SeasonType":"Regular Season","TeamID":1610612737},"resultSets":[{"name":"TeamInfoCommon","headers":["TEAM_ID","SEASON_YEAR","TEAM_CITY","TEAM_NAME","TEAM_ABBREVIATION","TEAM_CONFERENCE","TEAM_DIVISION","TEAM_CODE","W","L","PCT","CONF_RANK","DIV_RANK","MIN_YEAR","MAX_YEAR"],"rowSet":[[1610612737,"2014-15","Atlanta","Hawks","ATL","East","Southeast","hawks",60,22,0.732,1,1,"1949","2016"]]},{"name":"TeamSeasonRanks","headers":["LEAGUE_ID","SEASON_ID","TEAM_ID","PTS_RANK","PTS_PG","REB_RANK","REB_PG","AST_RANK","AST_PG","OPP_PTS_RANK","OPP_PTS_PG"],"rowSet":[["00","22014",1610612737,10,102.5,28,40.6,2,25.7,5,97.1]]}]}jj@jj-box:~/projects_dev/basket_io$```

Do you plan to fix it ?

Thanks,

Jakub

**Comment by seemethere** [comment]
@grillazz What about it doesn't work? The endpoint in nba_py as well as in curl seem to work.

**Comment by grillazz** [comment]
Hi @seemethere. Issue is bit wired. I'm working on Docker containers and when installing `nba_py` from `requirements.txt` everything is fine. But this is old version which is now in `master` branch. Next when adding this line `-e git+https://github.com/seemethere/nba_py.git@0.1a2#egg=nba-py` to `requirements.txt` and building containers I can see only `requests` lib installed properly :/ Also I can't reproduce issue this when manually installing `-e git+https://github.com/seemethere/nba_py.git@0.1a2#egg=nba-py` on local virtual env. So it looks that problem exists only in docker containers. :(

**Comment by grillazz** [comment]
Btw when I just copy/past you lib into project everything is working well :)

**Comment by seemethere** [comment]
Updated the package on pypi (https://github.com/seemethere/nba_py/commit/0fb85bf7845917b9caf70fc49833060ca4f1e08e) this shouldn't be a problem anymore.
