### ISSUE TITLE
player.get_player() marginalizes Nene

### ISSUE THREAD

**Issue by VitamintK** [seemethere/nba_py#56]
player.get_player() takes the required arguments: "first_name" and "last_name".  Nene, the unique flower that he is, only has one name, so the string formatting in this function will not work for him.

A fix would be to make the last_name argument optional, and perform string formatting differently for those with both names and those with only a first name.  Hopefully there's no NBA player with 3 names.

**Comment by seemethere** [comment]
Closed with #57
