### ISSUE TITLE
All players not present?

### ISSUE THREAD

**Issue by martendt** [seemethere/nba_py#58]
Hello, 

I'm trying to do a simple pull. Looking at a histogram of all player's points totals from past seasons. However, if I try to pull all player ID's from a past season:

pid_list = player.PlayerList(league_id=League.NBA,season='2010-11').info()['PERSON_ID']

For 2010-11, for instance, I only get a list of  ~70 players. Shouldn't there be more like 400?

**Comment by seemethere** [comment]
Set only_current to 0
