### ISSUE TITLE
Scoreboard access

### ISSUE THREAD

**Issue by martendt** [seemethere/nba_py#59]
Sorry, I know this is a simple request, but I can't seem to figure it out. To access a specific game ID I need to use the Scoreboard endpoint. What terms do I use to access scoreboard? I've tried:

newgame = game.Scoreboard()
... etc.
I know the "game" part is wrong, but I'm not sure what to replace it with.

**Comment by seemethere** [comment]
This should work:

```python
from nba_py import Scoreboard
s = Scoreboard()
game_ids = [item['GAME_ID'] for item in s.game_header()]
```
