### ISSUE TITLE
Errors running example_game

### ISSUE THREAD

**Issue by combinexnick** [seemethere/nba_py#63]
Noob here, quick question. Just downloaded repo and followed setup instructions (also ran setup.py build and setup.py install) and ran game_example.py to check it out. I'm able to successfully print out data from game.PlayByPlay, game.Boxscore, game.BoxscoreSummary, and game.PlayerTracking. However when I try to print data from game.BoxscoreScoring, game.BoxscoreUsage, game.BoxscoreMisc, game.BoxscoreAdvanced, or game.BoxscoreFourFactors I get a list index out of range error.

Seemingly it's only the functions with the "sql" prefix that won't work. Did I miss something in the setup? Sorry if there's an obvious answer here. Anyways, love what you are developing here. Thanks!

**Comment by seemethere** [comment]
Can you give me an example of the exact thing you are trying to ruN?

**Comment by combinexnick** [comment]
For example:

`from __future__ import print_function
from nba_py import game

bss = game.BoxscoreScoring('0041400122')
print(bss.sql_team_scoring())`

Then I'll get a list index out of range error from this line in _init_.py:

`headers = json_inp['resultSets'][ndx]['headers']`

**Comment by seemethere** [comment]
I see where the problem is, fix is on its way
