### ISSUE TITLE
Get Team Pace Stats

### ISSUE THREAD

**Issue by dbalders** [seemethere/nba_py#69]
Hey, I know your working on the new endpoints and documentation, but do you know how to get a team's pace stats or the player's pace stats? Looks like the endpoint url for the teams I want is:

    http://stats.nba.com/stats/leaguedashteamstats?Conference=&DateFrom=&DateTo=&Division=&GameScope=&GameSegment=&LastNGames=0&LeagueID=00&Location=&MeasureType=Advanced&Month=0&OpponentTeamID=0&Outcome=&PORound=0&PaceAdjust=N&PerMode=Totals&Period=0&PlayerExperience=&PlayerPosition=&PlusMinus=N&Rank=N&Season=2016-17&SeasonSegment=&SeasonType=Regular+Season&ShotClockRange=&StarterBench=&TeamID=0&VsConference=&VsDivision=

for the individual players it is:

    http://stats.nba.com/stats/leaguedashplayerstats?College=&Conference=&Country=&DateFrom=&DateTo=&Division=&DraftPick=&DraftYear=&GameScope=&GameSegment=&Height=&LastNGames=0&LeagueID=00&Location=&MeasureType=Advanced&Month=0&OpponentTeamID=0&Outcome=&PORound=0&PaceAdjust=N&PerMode=Totals&Period=0&PlayerExperience=&PlayerPosition=&PlusMinus=N&Rank=N&Season=2016-17&SeasonSegment=&SeasonType=Regular+Season&ShotClockRange=&StarterBench=&TeamID=0&VsConference=&VsDivision=&Weight=

But  I am not sure which functions to use in your program to get to those spots. Do you happen to know?

Thanks!

**Comment by proche90210** [comment]
**Install pandas then:** 
`from nba_py import league

l = league.TeamStats(season="2015-16", measure_type="Advanced")
df = l.overall()
print(df.PACE)
`

**Comment by dbalders** [comment]
great, thank you @proche90210
