### ISSUE TITLE
Can't install via pip

### ISSUE THREAD

**Issue by riririaan** [seemethere/nba_py#7]
Hey, I'm having trouble installing on pip with python 3.3 on mac. Any ideas? Not sure what the requirements should be. Pasted my terminal output and the full log below.

Cheers.

> pip install nba_py
Downloading/unpacking nba-py
  Could not find a version that satisfies the requirement nba-py (from versions: 0.1a1, 0.1a1.win-amd64, 0.1a1)
Cleaning up...
No distributions matching the version for nba-py
Storing debug log for failure in /Users/riaan/Library/Logs/pip.log

------------------------------------------------------------
/usr/local/bin/pip3 run on Tue Jan  5 22:06:03 2016
Downloading/unpacking nba-py

  Getting page https://pypi.python.org/simple/nba-py/
  URLs to search for versions for nba-py:
  * https://pypi.python.org/simple/nba-py/
  Analyzing links from page https://pypi.python.org/simple/nba-py/
    Skipping link https://pypi.python.org/packages/2.7/n/nba_py/nba_py-0.1a1-py2.7.egg#md5=7cacbd08f78013dd8c13df29e5a09667 (from https://pypi.python.org/simple/nba-py/); unknown archive format: .egg
    Skipping link https://pypi.python.org/packages/any/n/nba_py/nba_py-0.1a1.win-amd64.exe#md5=c2548bfd9e6ed8f1e97dbfe8a531da7d (from https://pypi.python.org/simple/nba-py/); unknown archive format: .exe
    Skipping link https://pypi.python.org/packages/py2.py3/n/nba_py/nba_py-0.1a1-py2.py3-none-any.whl#md5=fb0c1474acf89ff16437d65fadb7d2e1 (from https://pypi.python.org/simple/nba-py/); unknown archive format: .whl
    Found link https://pypi.python.org/packages/source/n/nba_py/nba_py-0.1a1.win-amd64.zip#md5=c7069634c9df944b47896180fb6e8ba6 (from https://pypi.python.org/simple/nba-py/), version: 0.1a1.win-amd64
    Found link https://pypi.python.org/packages/source/n/nba_py/nba_py-0.1a1.zip#md5=ca77e4f5dfd014ab5dfbf3184a7ade2d (from https://pypi.python.org/simple/nba-py/), version: 0.1a1
  Ignoring link https://pypi.python.org/packages/source/n/nba_py/nba_py-0.1a1.win-amd64.zip#md5=c7069634c9df944b47896180fb6e8ba6 (from https://pypi.python.org/simple/nba-py/), version 0.1a1.win-amd64 is a pre-release (use --pre to allow).
  Ignoring link https://pypi.python.org/packages/source/n/nba_py/nba_py-0.1a1.zip#md5=ca77e4f5dfd014ab5dfbf3184a7ade2d (from https://pypi.python.org/simple/nba-py/), version 0.1a1 is a pre-release (use --pre to allow).
  Could not find a version that satisfies the requirement nba-py (from versions: 0.1a1.win-amd64, 0.1a1)

Cleaning up...

  Removing temporary dir /private/var/folders/_v/hs6gcbb12n3187qjjmylqzgh0000gp/T/pip_build_riaan...
No distributions matching the version for nba-py

Exception information:
Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.3.3/Frameworks/Python.framework/Versions/3.3/lib/python3.3/site-packages/pip-1.4.1-py3.3.egg/pip/basecommand.py", line 134, in main
    status = self.run(options, args)
  File "/usr/local/Cellar/python3/3.3.3/Frameworks/Python.framework/Versions/3.3/lib/python3.3/site-packages/pip-1.4.1-py3.3.egg/pip/commands/install.py", line 236, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/usr/local/Cellar/python3/3.3.3/Frameworks/Python.framework/Versions/3.3/lib/python3.3/site-packages/pip-1.4.1-py3.3.egg/pip/req.py", line 1085, in prepare_files
    url = finder.find_requirement(req_to_install, upgrade=self.upgrade)
  File "/usr/local/Cellar/python3/3.3.3/Frameworks/Python.framework/Versions/3.3/lib/python3.3/site-packages/pip-1.4.1-py3.3.egg/pip/index.py", line 309, in find_requirement
    raise DistributionNotFound('No distributions matching the version for %s' % req)
pip.exceptions.DistributionNotFound: No distributions matching the version for nba-py

**Comment by moosemoosemoose** [comment]
Who are you? I never got it installed either.

**Comment by seemethere** [comment]
Looks like you might need to run the command with `--pre`:
```
pip install --pre nba_py
```

Let me know if that helps.

**Comment by riririaan** [comment]
I'll try that. I do know that it definitely installs successfully when
installing directly from github via

pip install git+https://github.com/seemethere/nba_py.git
