### ISSUE TITLE
video endpoint?

### ISSUE THREAD

**Issue by vladiki** [seemethere/nba_py#71]
Does anyone know which endpoint this website https://3ball.io is using to fetch videos?

I can see the videos are available here:
http://nba.cdn.turner.com/nba/big/nba/wsc/2016/09/19/79ae127b-b423-2df3-aec4-7467c13b038f.nba_286902_1920x1080_5904.mp4

Not sure how to get a full listing of them or go from game event_id to video.

**Comment by murrayLuke** [comment]
The endpoint was listed on the hacker news thread associated with the site. 

If you google this you can find more links to endpoints. inurl:xml site:nba.com

Here is where the videos are parsed from http://www.nba.com/video_sitemap_index.xml

Here is the hacker news thread with related info https://news.ycombinator.com/item?id=13163964

**Comment by vladiki** [comment]
I'm looking through that sitemap, these all look like they're from last year. Have you been able to find current videos through that sitemap?

**Comment by murrayLuke** [comment]
Couldn't find it try hitting him up on twitter.

**Comment by vladiki** [comment]
I think I got it figured out. From the play by play, each event can be accessed on its own page such as this http://stats.nba.com/events/#!/?flag=1&GameID=0021600361&GameEventID=25&Season=2016-17&title=MISS%20Kidd-Gilchrist%203'%20Layup&sct=plot

This page makes a request to an endpoint called 'videoevents' 
i.e http://stats.nba.com/stats/videoevents?GameEventID=25&GameID=0021600361

**Comment by murrayLuke** [comment]
not sure what happened to your comment but great job figuring that out

**Comment by vladiki** [comment]
Nah I deleted comment because it's incomplete. I got the uuid but its still not enough to come up with the full url. Ideally we are looking for something like 

http://nba.cdn.turner.com/nba/big/nba/wsc/2016/09/19/d94af74b-df2d-2e05-2e85-ea4ec1821050.nba_286185_1920x1080_5904.mp4

This gives us everything but the 286185 part, it seems the _1920x1080_5904 is consistent for all the videos, although it would be nice to figure out the full api and know the other sizes as well.

so right now I have http://nba.cdn.turner.com/nba/big/nba/wsc/2016/09/19/d94af74b-df2d-2e05-2e85-ea4ec1821050.nba_<x>_1920x1080_5904.mp4

Where I don't know how to get the <x> part.

**Comment by vladiki** [comment]
Okay, I got the final piece of the puzzle figured out. You can get all the urls for the videos and different video sizes from this xml call: http://www.nba.com/video/wsc/league/f8d850f9-4cfc-53a6-fb50-e3a690b23116.xml Where the argument is just the uuid from the video events endpoint. 

Anyone know off the top of their head if this package has any existing support for xml endpoints? Is this something we'd want to built into this package?

**Comment by murrayLuke** [comment]
I can look into it when im out of finals but thats really intereseting

**Comment by vladiki** [comment]
I think this package only supports json at the moment (https://github.com/seemethere/nba_py/blob/master/nba_py/__init__.py#L68)

We could add an a __get_xml method though. Should be possible to fetch the XML file using 'requests' and parse it using the native elementtree class (https://docs.python.org/2/library/xml.etree.elementtree.html). To match the json-based format of the rest of the package it'd be good to parse the xml in a separate method for this response and build out a sensible json version of the result.

**Comment by murrayLuke** [comment]
I think video support would be very interesting. I haven't seen any xml support but I'm sure there are libraries that support it quite easily.

**Comment by vladiki** [comment]
do you think its worth adding a new dependency on an xml library?

**Comment by seemethere** [comment]
the builtin xml library is just fine @vladiki

**Comment by vladiki** [comment]
I think we'll have to build a custom xml to json generator for every xml endpoint though to keep the interface to the data consistent because I don't think theres a straightforward xml to json conversion http://stackoverflow.com/questions/191536/converting-xml-to-json-using-python.

**Comment by seemethere** [comment]
@vladiki I actually have a function to do exactly this, will post it tomorrow

**Comment by murrayLuke** [comment]
It may also be important to convert xml to pandas dataframe
