### ISSUE TITLE
Showing Matchups!

### ISSUE THREAD

**Issue by NachoCalcagno** [seemethere/nba_py#8]
Hello man, i just found your documentation about nba stats, really good stuff, because all ive found it was like payed api. Im practicing some coding on Ruby, just trying to display daily matchups, For example, i wanna show today games, ill use  "stats.nba.com/stats/scoreboard/?GameDate=09/01/2016&LeagueID=00&DayOffset=0",is that correct? or i have to use other endpoint? i can find each team on each conference, but i dont get it to get the daily games. Sorry about my grammar, English isnt my first language :).

Short problem: I just want to find the daily games, ex : Chicago vs Atlanta

Thanks!

**Comment by seemethere** [comment]
The date format for the scoreboard endpoint is actually MM/DD/YYYY
This one should work:

http://stats.nba.com/stats/scoreboard/?GameDate=01/09/2016&LeagueID=00&DayOffset=0
