### ISSUE TITLE
Getting all players' current season advanced stats

### ISSUE THREAD

**Issue by goedken** [seemethere/nba_py#81]
New to using the API, but I was trying to get every current player's advanced stats for the current season. Here's my code:
```
from nba_py import player
players = player.PlayerList(season='2016-17')
data = []
for index, row in players.info().iterrows():
    curr_player = player.PlayerGeneralSplits(row['PERSON_ID'], measure_type='Advanced')
    curr_player_ovr = curr_player.overall()
    data.insert(index, curr_player_ovr)
print data
```

This is taking a while. Maybe there's a faster way to add the results to an array (I want to eventually output it all to a JSON file). I'm somewhat new to python. Is it my code that's causing this to take a while (probably around ten minutes), or is it just because the API has to go scrape all of the data.

Thanks for making this API by the way!

**Comment by proche90210** [comment]
**Install Pandas then try**

`from nba_py import league
import pandas as pd

# print to console without the dots in between
pd.set_option('display.width', 3000)
pd.set_option('display.max_columns', 100)
pd.set_option('display.max_rows', 10000)

l = league.PlayerStats(measure_type="Advanced")
df = l.overall()
print(df)
`

This gives back the a lot of info on players this season.
 Hope this helps.

**Comment by goedken** [comment]
Wow, this was a lot faster, thanks! However, when I try to save it as json with `df.to_json('path')` it formats as 
```
{
    "PLAYER_ID": {
        "0":1627773,
        "1": // and so on
     },
     "PLAYER_NAME": {
         "0":"AJ Hammons",
         "1": // and so on
      },
      // and then each attribute like this
}
```
Is it possible to save it so that json goes by row rather than column?

This was the full solution I had with my way:
```
data = []
for index, row in players.info().iterrows():
    curr_player = player.PlayerGeneralSplits(row['PERSON_ID'], measure_type='Advanced')
    curr_player_ovr = curr_player.overall()
    curr_player_ovr['PERSON_ID'] = row['PERSON_ID']
    curr_player_sum = player.PlayerSummary(row['PERSON_ID']).info()
    curr_player_headline = player.PlayerSummary(row['PERSON_ID']).headline_stats()
    curr_player_headline['PERSON_ID'] = row['PERSON_ID']
    final_player = curr_player_sum.merge(curr_player_headline, on='PERSON_ID').merge(curr_player_ovr, on='PERSON_ID')
    cols = [c for c in final_player.columns if "RANK" not in c]
    final_player = final_player[cols]
    final_player.rename(columns=lambda x: x.lower(), inplace=True)
    data.insert(index, final_player.to_json())

with open('path', 'w') as outfile:  
    json.dump(data, outfile)
```
        
I feel like an idiot for not looking at 'league' earlier. Thanks for your help.

**Comment by proche90210** [comment]
Try df.to_json(path="whereever", orient="records")

orient="records" should do the trick

Just a tip from my own experience, try to find a command that has all the
data you want in one command then do the work on your side.

Looping over sending multiple requests is very slow.

**Comment by vlinsane** [comment]
@proche90210 how long does it take to get results from your code? Took me 155 seconds. Seems slow.

**Comment by proche90210** [comment]
That's very slow. That http call takes around 3-5 seconds on mine.
Sometimes less.

Did it copy and paste it exactly?

**Comment by vlinsane** [comment]
Problem solved. 

I tried to run the same code on the same laptop on a different internet connection (same ISP) and it took 1.5 seconds! I checked the internet connection and noticed that the IPv6 was NOT set. On my home network it was set. I changed my home router settings and now it takes only 1.5 seconds.
