### ISSUE TITLE
playerdashptshotlog is broken

### ISSUE THREAD

**Issue by StephenCronin** [seemethere/nba_py#9]
Not sure if NBA changed the API or not, but the shot logs,  probably the most cool data endpoint doesn't exist any more.  How did you define the endpoint space in the first place?  maybe they changed the url?

**Comment by seemethere** [comment]
The way I had found all the endpoints was through a constants file found by going through the js files in the console. The file was named feeds.js and it seems as though the NBA has taken these away and is slowly limiting their outward facing API as more and more people become aware of it.

All of the endpoints seem to work as expected aside from these in particular:
playerdashboardbygeneralsplits
playerdashboardbyopponent
playerdashboardbyshootingsplits
playerdashptshotlog
playerdashptreboundlogs
